name: final_stairs_pretrained_extra_reward_thesis_${seed}
comment:
  Random stairs, starting from pretrained trunk model, last multi seed run for thesis, extra reward for step ascent
  the trunk crossing task
seed: 42
use_wandb: false
eval_repeats_after_training: 20
use_tensorboard: false
device: cuda:0
training_dtype: ${dtype:float32}
total_frames: ${mul:5242880,3}
engine_iters_per_env_step: 4
num_robots: 256
time_steps_per_batch: 128
epochs_per_batch: 5
frames_per_sub_batch: 4096
eval_and_save_every: 10
max_eval_steps: 500
optimizer: ${cls:torch.optim.AdamW}
scheduler: ${cls:torch.optim.lr_scheduler.LinearLR}
scheduler_opts:
  start_factor: 1.0
  end_factor: 0.5618372186349603
  total_iters: ${intdiv:${total_frames},${mul:${time_steps_per_batch},${num_robots}}}
max_grad_norm: 0.5
grid_res: 0.05
max_coord: 3.2
heightmap_gen: ${ cls:flipper_training.heightmaps.stairs.StairsHeightmapGenerator}
heightmap_gen_opts:
  min_steps: 3
  max_steps: 8
  min_step_height: 0.15
  max_step_height: 0.4
  exponent: null
world_opts:
  k_stiffness: 35000
  k_friction_lon: 0.8
  k_friction_lat: 0.5
engine_opts:
  damping_alpha: 5.0
  dt: 0.007
engine_compile_opts:
  options:
    triton.cudagraphs: true
  fullgraph: true
  correctness_iters: 10
  benchmark_iters: 1000
  atol: 0.1
  rtol: 1.0e-06
robot_model_opts:
  kind: marv
  mesh_voxel_size: 0.01
  points_per_driving_part: 384
  points_per_body: 512
  wheel_assignment_margin: 0.02
  linear_track_assignment_margin: 0.05
vecnorm_opts:
  decay: 0.99
  eps: 0.0001
vecnorm_on_reward: true
observations:
  - cls: ${cls:flipper_training.observations.robot_state.LocalStateVector}
    opts:
      apply_noise: true
      noise_scale: 1.0e-05
      encoder_opts:
        num_hidden: 2
        hidden_dim: 64
        output_dim: 64
        layernorm: true
  - cls: ${cls:flipper_training.observations.heightmap.Heightmap}
    opts:
      apply_noise: true
      noise_scale: 1.0e-05
      percep_shape:
        - 64
        - 64
      percep_extent:
        - 1.0
        - 1.0
        - -1.0
        - -1.0
      interval:
        - -1.0
        - 1.0
      normalize_to_interval: false
      encoder_opts:
        output_dim: 64
gae_opts:
  gamma: 0.999
  lmbda: 0.95
  average_gae: false
  skip_existing: false
ppo_opts:
  clip_epsilon: 0.2
  entropy_bonus: true
  entropy_coef: 0.02
  critic_coef: 1.0
  loss_critic_type: smooth_l1
  normalize_advantage: true
  separate_losses: false
data_collector_opts:
  compile_policy: false
  split_trajs: false
  exploration_type: RANDOM
objective: ${cls:flipper_training.rl_objectives.stair_crossing.StairCrossing}
objective_opts:
  goal_reached_threshold: 0.2
  start_z_offset: 0.3
  goal_z_offset: 0.1
  iteration_limit_factor: 8
  max_feasible_pitch: 1.5
  max_feasible_roll: 1.5
  start_position_orientation: towards_goal
  cache_size: 40000
  sampling_mode: any
  min_dist_from_edge: 0.5
  init_joint_angles: random
  resample_random_joint_angles_on_reset: true
reward: ${cls:flipper_training.rl_rewards.rewards.PotentialGoalWithStepAscentBonus}
reward_opts:
  goal_reached_reward: 7.326022319628405
  failed_reward: -8.086958618117405
  potential_coef: 61.755824567422465
  gamma: ${gae_opts.gamma}
  step_penalty: -0.3760019567268228
  step_bonus_coef: 0.15275583154628047
policy_config: ${cls:flipper_training.policies.mlp_policy.MLPPolicyConfig}
policy_opts:
  share_encoder: false
  apply_baselines_init: true
  actor_mlp_opts:
    num_hidden: 2
    hidden_dim: 64
    layernorm: false
  value_mlp_opts:
    num_hidden: 2
    hidden_dim: 64
    layernorm: true
  actor_optimizer_opts:
    lr: 0.00014521174983010248
    weight_decay: 0.0001
  value_optimizer_opts:
    lr: 0.0025380292738310236
    weight_decay: 0.0001
policy_weights_path: runs/ppo/random_trunk_with_control_smoothness_penalties_2025-05-04_20-33-47/weights/policy_final.pth
vecnorm_weights_path: runs/ppo/random_trunk_with_control_smoothness_penalties_2025-05-04_20-33-47/weights/vecnorm_final.pth
