repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Use the latest version of Ruff
    rev: v0.9.10
    hooks:
      # Run the linter with fixes, ignore notebooks
      - id: ruff
        args:
          - "--fix"
          - "--line-length=150"
          - "--extend-select=E,F,Q,B,S"
          - "--extend-exclude=\\.ipynb$"
      # Run the formatter
      - id: ruff-format
        args: ["--line-length=150"]
