name: deterministic_trunk_debug_for_hparam_calibration
comment: Debugging PPO on trunk terrain with fixed goal navigation
seed: 42
use_wandb: true
use_tensorboard: false
device: cuda:2
training_dtype: ${dtype:float32}
total_frames: ${mul:5242880,6}
frames_per_batch: 128
epochs_per_batch: 1
frames_per_sub_batch: 64
eval_and_save_every: 10
max_eval_steps: 900
optimizer: ${cls:torch.optim.AdamW}
scheduler: ${cls:torch.optim.lr_scheduler.ExponentialLR}
scheduler_opts:
  gamma: 0.999
max_grad_norm: 0.5
num_robots: 128
grid_res: 0.05
max_coord: 3.2
heightmap_gen: ${ cls:flipper_training.heightmaps.trunks.FixedTrunkHeightmapGenerator}
heightmap_gen_opts:
  trunk_height: 0.2
  trunk_width: 0.8
world_opts:
  k_stiffness: 30000
  k_friction_lon: 0.8
  k_friction_lat: 0.5
engine_opts:
  damping_alpha: 4.0
  dt: 0.01
engine_compile_opts:
  max-autotune: true
  triton.cudagraphs: true
  coordinate_descent_tuning: true
  correctness_iters: 100
  benchmark_iters: 1000
  atol: 1
  rtol: 0
robot_model_opts:
  kind: marv
  mesh_voxel_size: 0.01
  points_per_driving_part: 384
  points_per_body: 512
  wheel_assignment_margin: 0.02
  linear_track_assignment_margin: 0.05
vecnorm_opts:
  decay: 0.99
  eps: 0.0001
vecnorm_on_reward: true
observations:
  - cls: ${cls:flipper_training.observations.robot_state.LocalStateVector}
    opts:
      encoder_opts:
        num_hidden: 4
        hidden_dim: 64
        output_dim: 64
  - cls: ${cls:flipper_training.observations.heightmap.Heightmap}
    opts:
      percep_shape: [64, 64]
      percep_extent: [1.0, 1.0, -1.0, -1.0]
      encoder_opts:
        output_dim: 128
gae_opts:
  gamma: 0.999
  lmbda: 0.95
  average_gae: false
  skip_existing: false
gae_compile_opts: null
ppo_opts:
  clip_epsilon: 0.2
  entropy_bonus: true
  entropy_coef: 0.02
  critic_coef: 1.0
  loss_critic_type: smooth_l1
  normalize_advantage: false
  separate_losses: false
ppo_compile_opts: null
data_collector_opts:
  split_trajs: false
  compile_policy: true
  exploration_type: RANDOM
objective: ${cls:flipper_training.rl_objectives.fixed_goal.FixedStartGoalNavigation}
objective_opts:
  start_x_y_z: ${tensor:[-1.5, 0.0, 0.2]}
  goal_x_y_z: ${tensor:[1.5, 0.0, 0.05]}
  iteration_limit: 900
  max_feasible_pitch: 1.5
  max_feasible_roll: 1.5
  goal_reached_threshold: 0.2
  init_joint_angles: random
  resample_random_joint_angles_on_reset: true
reward: ${cls:flipper_training.rl_rewards.rewards.PotentialGoal}
reward_opts:
  goal_reached_reward: 100.0
  failed_reward: -100.0
  potential_coef: 20
  gamma: ${gae_opts.gamma}
  step_penalty: -0.02
policy_config: ${cls:flipper_training.policies.mlp_policy.MLPPolicyConfig}
policy_opts:
  share_encoder: false
  apply_baselines_init: true
  actor_mlp_opts:
    num_hidden: 4
    hidden_dim: 128
    layernorm: false
  value_mlp_opts:
    num_hidden: 4
    hidden_dim: 128
    layernorm: true
  actor_optimizer_opts:
    lr: 0.0001
    weight_decay: 1.0e-05
  value_optimizer_opts:
    lr: 0.001
    weight_decay: 1.0e-05
