# General Experiment Configuration
type: ${cls:flipper_training.experiments.ppo.config.PPOExperimentConfig}
name: deterministic_flats_debug_for_hparam_calibration
comment: "Debugging PPO on flat terrain with fixed goal navigation"
seed: 42
use_wandb: true
use_tensorboard: false
device: cuda:0

# Training Loop Parameters
training_dtype: ${dtype:float32}
total_frames: ${mul:5242880,4}
frames_per_batch: 128
epochs_per_batch: 1
frames_per_sub_batch: 64 # Must divide frames_per_batch * num_robots
eval_and_save_every: 10 # steps
max_eval_steps: 500

# Optimizer and Scheduler Configuration
optimizer: ${cls:torch.optim.AdamW}
scheduler: ${cls:torch.optim.lr_scheduler.StepLR}
scheduler_opts:
  step_size: ${intdiv:${intdiv:${total_frames},${mul:${frames_per_batch},${num_robots}}},4}
  gamma: 0.7
max_grad_norm: 0.5

# Environment and Simulation Settings
num_robots: 16
grid_res: 0.05
max_coord: 3.2
heightmap_gen: ${ cls:flipper_training.heightmaps.flat.FlatHeightmapGenerator}
heightmap_gen_opts: {}
world_opts:
  k_stiffness: 30000
  k_friction_lon: 0.8
  k_friction_lat: 0.5
engine_opts:
  damping_alpha: 5.0
  dt: 0.01
engine_compile_opts:
  max-autotune: true
  triton.cudagraphs: true
  coordinate_descent_tuning: true
  correctness_iters: 100
  benchmark_iters: 1000
  atol: 1
  rtol: 0

# Robot Model Configuration
robot_model_opts:
  kind: marv
  mesh_voxel_size: 0.01
  points_per_driving_part: 384
  points_per_body: 512
  wheel_assignment_margin: 0.02
  linear_track_assignment_margin: 0.05

# Observation and Normalization Settings
vecnorm_opts:
  decay: 0.99
  eps: 1e-4
vecnorm_on_reward: true
observations:
  - cls: ${cls:flipper_training.observations.robot_state.LocalStateVector}
    opts:
      encoder_opts:
        num_hidden: 2
        hidden_dim: 32
        output_dim: 32

# PPO Algorithm Parameters
gae_opts:
  gamma: 0.99
  lmbda: 0.95
  average_gae: false
  skip_existing: false
gae_compile_opts: null # Optional compilation settings for GAE calculation
ppo_opts:
  clip_epsilon: 0.2
  entropy_bonus: true
  entropy_coef: 0.02
  critic_coef: 1.0
  loss_critic_type: smooth_l1
  normalize_advantage: false
ppo_compile_opts: null # Optional compilation settings for PPO
data_collector_opts:
  split_trajs: false
  compile_policy: true
  exploration_type: RANDOM

# Task Objective Configuration
objective: ${cls:flipper_training.rl_objectives.fixed_goal.FixedStartGoalNavigation}
objective_opts:
  start_x_y_z: ${tensor:[-1.5, 0.0, 0.2]}
  goal_x_y_z: ${tensor:[1.5, 0.0, 0.05]}
  iteration_limit: 500
  max_feasible_pitch: 1.5
  max_feasible_roll: 1.5
  goal_reached_threshold: 0.1
  init_joint_angles: random
  resample_random_joint_angles_on_reset: true

# Reward Function Configuration
reward: ${cls:flipper_training.rl_rewards.rewards.PotentialGoalRelativized}
reward_opts:
  goal_reached_reward: 100.0
  failed_reward: -100.0
  step_penalty: -5e-2
  gamma: ${gae_opts.gamma} # Should match GAE gamma
  potential_coef: 1.0
  eps: 0.2

## Policy and Value Network Architecture
policy_config: ${cls:flipper_training.policies.mlp_policy.MLPPolicyConfig}
policy_opts:
  share_encoder: false
  actor_mlp_opts:
    num_hidden: 1
    hidden_dim: 32
    layernorm: false
  value_mlp_opts:
    num_hidden: 1
    hidden_dim: 32
    layernorm: false
  actor_optimizer_opts:
    lr: 3e-4
    weight_decay: 1e-3
  value_optimizer_opts:
    lr: 5e-4
    weight_decay: 1e-3
