name: random_trunk_for_hparam_calibration
comment: Fixed trunk heightmap with random start and goal positions
seed: 42
use_wandb: true
eval_repeats_after_training: 1
use_tensorboard: false
device: cuda
training_dtype: ${dtype:float32}
total_frames: ${mul:5242880,3}
engine_iters_per_env_step: 4
num_robots: 256
time_steps_per_batch: 128
epochs_per_batch: 5
frames_per_sub_batch: 4096
eval_and_save_every: 10
max_eval_steps: 400
optimizer: ${cls:torch.optim.AdamW}
# scheduler: ${cls:torch.optim.lr_scheduler.LinearLR}
# scheduler_opts:
#   start_factor: 1.0
#   end_factor: 0.1
#   total_iters: 320 # ${intdiv:${total_frames},${mul:${time_steps_per_batch},${num_robots}}}
scheduler: ${cls:flipper_training.utils.schedulers.LinearDecayThenConstantLR}
scheduler_opts:
  end_factor: 0.1
  end_step: 320
max_grad_norm: 0.5
grid_res: 0.05
max_coord: 3.2
heightmap_gen: ${ cls:flipper_training.heightmaps.trunks.FixedTrunkHeightmapGenerator}
heightmap_gen_opts:
  trunk_height: 0.2
  trunk_width: 0.8
world_opts:
  k_stiffness: 35000
  k_friction_lon: 0.8
  k_friction_lat: 0.5
engine_opts:
  damping_alpha: 5.0
  dt: 0.007
engine_compile_opts:
  # options:
  #   triton.cudagraphs: true
  #   max-autotune: true
  #   coordinate_descent_tuning: true
  fullgraph: true
  correctness_iters: 200
  benchmark_iters: 1000
  atol: 1e-2
  rtol: 1e-6
robot_model_opts:
  kind: marv
  mesh_voxel_size: 0.01
  points_per_driving_part: 384
  points_per_body: 512
  wheel_assignment_margin: 0.02
  linear_track_assignment_margin: 0.05
vecnorm_opts:
  decay: 0.99
  eps: 0.0001
vecnorm_on_reward: true
observations:
  - cls: ${cls:flipper_training.observations.robot_state.LocalStateVector}
    opts:
      encoder_opts:
        num_hidden: 2
        hidden_dim: 64
        output_dim: 64
        layernorm: true
  - cls: ${cls:flipper_training.observations.heightmap.Heightmap}
    opts:
      percep_shape: [64, 64]
      percep_extent: [1.0, 1.0, -1.0, -1.0]
      interval: [-1.0, 1.0]
      normalize_to_interval: false
      encoder_opts:
        output_dim: 64
gae_opts:
  gamma: 0.999
  lmbda: 0.95
  average_gae: false
  skip_existing: false
gae_compile_opts: null
ppo_opts:
  clip_epsilon: 0.2
  entropy_bonus: true
  entropy_coef: 0.02
  critic_coef: 1.0
  loss_critic_type: smooth_l1
  normalize_advantage: true
  separate_losses: false
ppo_compile_opts: null
data_collector_opts:
  compile_policy: false
  split_trajs: false
  exploration_type: RANDOM
objective: ${cls:flipper_training.rl_objectives.trunk_crossing.TrunkCrossing}
objective_opts:
  min_dist_to_goal: 2.0
  max_dist_to_goal: 4.0
  iteration_limit_factor: 5
  max_feasible_pitch: 1.5
  max_feasible_roll: 1.5
  start_z_offset: 0.2
  goal_z_offset: 0.05
  goal_reached_threshold: 0.2
  start_position_orientation: towards_goal
  init_joint_angles: random
  resample_random_joint_angles_on_reset: true
  cache_size: 12000
reward: ${cls:flipper_training.rl_rewards.rewards.PotentialGoal}
reward_opts:
  goal_reached_reward: 5.0
  failed_reward: -5.0
  potential_coef: 20
  gamma: ${gae_opts.gamma}
  step_penalty: -0.1
policy_config: ${cls:flipper_training.policies.mlp_policy.MLPPolicyConfig}
policy_opts:
  share_encoder: false
  apply_baselines_init: true
  actor_mlp_opts:
    num_hidden: 2
    hidden_dim: 64
    layernorm: false
  value_mlp_opts:
    num_hidden: 2
    hidden_dim: 64
    layernorm: true
  actor_optimizer_opts:
    lr: 0.0002
    weight_decay: 1e-4
  value_optimizer_opts:
    lr: 0.001
    weight_decay: 1e-4
