name: coarse_gaussian_terrain_smoothness
comment: Random coarse gaussian terrain with random start and goal, pretrained weights and smoothness penalties
seed: 42
use_wandb: true
eval_repeats_after_training: 1
use_tensorboard: false
device: cuda:0
training_dtype: ${dtype:float32}
total_frames: ${mul:5242880,5}
engine_iters_per_env_step: 4
num_robots: 256
time_steps_per_batch: 128
epochs_per_batch: 5
frames_per_sub_batch: 4096
eval_and_save_every: 10
max_eval_steps: 500
optimizer: ${cls:torch.optim.AdamW}
scheduler: ${cls:torch.optim.lr_scheduler.LinearLR}
scheduler_opts:
  start_factor: 1.0
  end_factor: 0.20079129348367777
  total_iters: ${intdiv:${total_frames},${mul:${time_steps_per_batch},${num_robots}}}
max_grad_norm: 0.5
grid_res: 0.05
max_coord: 3.2
heightmap_gen: ${ cls:flipper_training.heightmaps.multi_gaussian.MultiGaussianHeightmapGenerator}
heightmap_gen_opts:
  min_gaussians: 100
  max_gaussians: 200
  min_height_fraction: 0.05
  max_height_fraction: 0.2
  min_std_fraction: 0.1
  max_std_fraction: 0.18
  min_sigma_ratio: 0.6
  top_height_percentile_cutoff: 0.7
world_opts:
  k_stiffness: 30000
  k_friction_lon: 1.0
  k_friction_lat: 0.8
engine_opts:
  damping_alpha: 5.0
  dt: 0.007
engine_compile_opts:
  options:
    triton.cudagraphs: true
  fullgraph: true
  correctness_iters: 10
  benchmark_iters: 1000
  atol: 0.1
  rtol: 1.0e-06
robot_model_opts:
  kind: marv
  mesh_voxel_size: 0.01
  points_per_driving_part: 384
  points_per_body: 512
  wheel_assignment_margin: 0.02
  linear_track_assignment_margin: 0.05
vecnorm_opts:
  decay: 0.99
  eps: 0.0001
vecnorm_on_reward: true
observations:
  - cls: ${cls:flipper_training.observations.robot_state.LocalStateVector}
    opts:
      apply_noise: true
      noise_scale: 1.0e-05
      encoder_opts:
        num_hidden: 2
        hidden_dim: 64
        output_dim: 64
        layernorm: true
  - cls: ${cls:flipper_training.observations.heightmap.Heightmap}
    opts:
      apply_noise: true
      noise_scale: 1.0e-05
      percep_shape:
        - 64
        - 64
      percep_extent:
        - 1.0
        - 1.0
        - -1.0
        - -1.0
      interval:
        - -1.0
        - 1.0
      normalize_to_interval: false
      encoder_opts:
        output_dim: 64
gae_opts:
  gamma: 0.999
  lmbda: 0.95
  average_gae: false
  skip_existing: false
ppo_opts:
  clip_epsilon: 0.2
  entropy_bonus: true
  entropy_coef: 0.02
  critic_coef: 1.0
  loss_critic_type: smooth_l1
  normalize_advantage: true
  separate_losses: false
data_collector_opts:
  compile_policy: false
  split_trajs: false
  exploration_type: RANDOM
objective: ${cls:flipper_training.rl_objectives.random_nav.RandomNavigationObjective}
objective_opts:
  goal_reached_threshold: 0.3
  start_z_offset: 0.3
  goal_z_offset: 0.15
  iteration_limit_factor: 5
  min_dist_to_goal: 2.0
  max_dist_to_goal: 4.0
  max_feasible_pitch: 1.5
  max_feasible_roll: 1.5
  start_position_orientation: towards_goal
  higher_allowed: 0.5
  cache_size: 40000
  init_joint_angles: random
reward: ${cls:flipper_training.rl_rewards.rewards.PotentialGoalWithPenaltiesConfigurable}
reward_opts:
  goal_reached_reward: 9.226219446495175
  failed_reward: -9.218539745909489
  potential_coef: 41.652884613488965
  gamma: ${gae_opts.gamma}
  step_penalty: -0.3371775776356437
  joint_vel_variance_coef: 0.5
  joint_angle_variance_coef: 0.5
  track_vel_variance_coef: 0.5
  roll_coef: 0.5
  pitch_coef: 0.5
  roll_rate_coef: 0.5
  pitch_rate_coef: 0.5
policy_config: ${cls:flipper_training.policies.mlp_policy.MLPPolicyConfig}
policy_opts:
  share_encoder: false
  apply_baselines_init: true
  actor_mlp_opts:
    num_hidden: 2
    hidden_dim: 64
    layernorm: false
  value_mlp_opts:
    num_hidden: 2
    hidden_dim: 64
    layernorm: true
  actor_optimizer_opts:
    lr: 0.0001
    weight_decay: 0.0001
  value_optimizer_opts:
    lr: 0.001
    weight_decay: 0.0001
policy_weights_path: runs/ppo/final_mixed_objective_training_666_2025-05-16_19-08-25/weights/policy_final.pth
vecnorm_weights_path: runs/ppo/final_mixed_objective_training_666_2025-05-16_19-08-25/weights/vecnorm_final.pth
