# General Experiment Configuration
type: ${cls:flipper_training.experiments.ppo.config.PPOExperimentConfig}
name: random_flat_debug_gpu_potential
comment: "Debugging PPO on flat terrain with randomized start and goal"
seed: 42
use_wandb: true
device: cuda:0

# Training Loop Parameters
training_dtype: ${dtype:float32}
total_frames: ${mul:5242880,1}
frames_per_batch: 128
epochs_per_batch: 1
frames_per_sub_batch: 64 # Must divide frames_per_batch * num_robots
eval_and_save_every: 10 # steps
max_eval_steps: 900

# Optimizer and Scheduler Configuration
optimizer: ${cls:torch.optim.AdamW}
optimizer_opts:
  actor:
    lr: 3e-4
    weight_decay: 1e-3
  critic:
    lr: 1e-3
    weight_decay: 1e-3
scheduler: ${cls:torch.optim.lr_scheduler.StepLR}
scheduler_opts:
  step_size: ${intdiv:${intdiv:${total_frames},${mul:${frames_per_batch},${num_robots}}},2}
  gamma: 0.5
max_grad_norm: 1.0

# Environment and Simulation Settings
num_robots: 128
grid_res: 0.05
max_coord: 3.2
heightmap_gen: ${ cls:flipper_training.heightmaps.flat.FlatHeightmapGenerator}
heightmap_gen_opts: {}
world_opts:
  k_stiffness: 30000
  k_friction_lon: 0.8
  k_friction_lat: 0.5
engine_opts:
  damping_alpha: 5.0
  dt: 0.01
engine_compile_opts:
  max-autotune: true
  triton.cudagraphs: true
  coordinate_descent_tuning: true
  correctness_iters: 100
  benchmark_iters: 1000
  atol: 1
  rtol: 0

# Robot Model Configuration
robot_model_opts:
  kind: marv
  mesh_voxel_size: 0.01
  points_per_driving_part: 384
  points_per_body: 512
  wheel_assignment_margin: 0.02
  linear_track_assignment_margin: 0.05

# Observation and Normalization Settings
vecnorm_opts:
  decay: 0.95
  eps: 1e-4
vecnorm_on_reward: true
observations:
  state:
    observation: ${cls:flipper_training.observations.robot_state.LocalStateVector}
    opts: {}
observation_encoders_opts:
  state:
    output_dim: 32
    hidden_dim: 32
    num_hidden: 1
    ln: true

# PPO Algorithm Parameters
gae_opts:
  gamma: 0.99
  lmbda: 0.95
  average_gae: false
  skip_existing: false
gae_compile_opts: null # Optional compilation settings for GAE calculation
ppo_opts:
  clip_epsilon: 0.2
  entropy_bonus: true
  entropy_coef: 0.02
  critic_coef: 1.0
  loss_critic_type: smooth_l1
  normalize_advantage: false
ppo_compile_opts: null # Optional compilation settings for PPO
data_collector_opts:
  split_trajs: false
  compile_policy: true
  exploration_type: RANDOM

# Task Objective Configuration
objective: ${cls:flipper_training.rl_objectives.random_nav.RandomNavigationObjective}
objective_opts:
  higher_allowed: 0.5
  min_dist_to_goal: 0.5
  max_dist_to_goal: 3.0
  start_z_offset: 0.2
  goal_z_offset: 0.05
  goal_reached_threshold: 0.1
  iteration_limit_factor: 5
  max_feasible_pitch: 1.5
  max_feasible_roll: 1.5
  start_position_orientation: towards_goal
  cache_size: 30000

# Reward Function Configuration
reward: ${cls:flipper_training.rl_rewards.rewards.PotentialGoalWithConditionalVelocityBonus}
reward_opts:
  goal_reached_reward: 200.0
  failed_reward: -200.0
  step_penalty: -1e-1
  gamma: ${gae_opts.gamma} # Should match GAE gamma
  potential_coef: 20.0
  velocity_bonus_coef: 0.1

# Policy and Value Network Architecture
policy_opts:
  hidden_dim: 32
  num_hidden: 1
  ln: false
value_function_opts:
  hidden_dim: 32
  num_hidden: 1
  ln: false
