name: barrier_with_preference_parameters
comment: Random barrier with random start and goal positions and latent control parameters to make the robot swerve right or left
seed: 42
use_wandb: true
eval_repeats_after_training: 1
use_tensorboard: false
device: cuda
training_dtype: ${dtype:float32}
total_frames: ${mul:5242880,6}
engine_iters_per_env_step: 4
num_robots: 256
time_steps_per_batch: 128
epochs_per_batch: 5
frames_per_sub_batch: 4096
eval_and_save_every: 10
max_eval_steps: 1000
optimizer: ${cls:torch.optim.AdamW}
scheduler: ${cls:torch.optim.lr_scheduler.LinearLR}
scheduler_opts:
  start_factor: 1.0
  end_factor: 0.2345794068901917
  total_iters: ${intdiv:${total_frames},${mul:${time_steps_per_batch},${num_robots}}}
max_grad_norm: 0.5
grid_res: 0.05
max_coord: 3.2
heightmap_gen: ${ cls:flipper_training.heightmaps.barrier.BarrierHeightmapGenerator}
heightmap_gen_opts:
  min_length: 0.5
  max_length: 2.5
  min_thickness: 0.8
  max_thickness: 1.2
  max_dist_from_origin: 0.5
  deadzone: 0.2
  min_height: 0.1
  max_height: 0.5
  exp: 20
world_opts:
  k_stiffness: 35000
  k_friction_lon: 0.8
  k_friction_lat: 0.5
engine_opts:
  damping_alpha: 5.0
  dt: 0.007
engine_compile_opts:
  options:
    triton.cudagraphs: true
  fullgraph: true
  correctness_iters: 10
  benchmark_iters: 1000
  atol: 0.1
  rtol: 1.0e-06
robot_model_opts:
  kind: marv
  mesh_voxel_size: 0.01
  points_per_driving_part: 384
  points_per_body: 512
  wheel_assignment_margin: 0.02
  linear_track_assignment_margin: 0.05
vecnorm_opts:
  decay: 0.99
  eps: 0.0001
vecnorm_on_reward: true
observations:
  - cls: ${cls:flipper_training.observations.robot_state.LocalStateVector}
    opts:
      apply_noise: true
      noise_scale: 1.0e-05
      encoder_opts:
        num_hidden: 2
        hidden_dim: 64
        output_dim: 64
        layernorm: true
  - cls: ${cls:flipper_training.observations.heightmap.Heightmap}
    opts:
      apply_noise: true
      noise_scale: 1.0e-05
      percep_shape:
        - 64
        - 64
      percep_extent:
        - 1.0
        - 1.0
        - -1.0
        - -1.0
      interval:
        - -1.0
        - 1.0
      normalize_to_interval: false
      encoder_opts:
        output_dim: 64
  - cls: ${cls:flipper_training.observations.latent_control.LatentControlParameter}
gae_opts:
  gamma: 0.999
  lmbda: 0.95
  average_gae: false
  skip_existing: false
ppo_opts:
  clip_epsilon: 0.2
  entropy_bonus: true
  entropy_coef: 0.02
  critic_coef: 1.0
  loss_critic_type: smooth_l1
  normalize_advantage: true
  separate_losses: false
data_collector_opts:
  compile_policy: false
  split_trajs: false
  exploration_type: RANDOM
objective: ${cls:flipper_training.rl_objectives.barrier_crossing_latent.BarrierCrossingWithLatentControl}
objective_opts:
  min_dist_to_goal: 2.0
  max_dist_to_goal: 4.0
  iteration_limit_factor: 10
  max_feasible_pitch: 1.5
  max_feasible_roll: 1.5
  start_z_offset: 0.2
  goal_z_offset: 0.05
  goal_reached_threshold: 0.2
  start_position_orientation: towards_goal
  init_joint_angles: random
  resample_random_joint_angles_on_reset: true
  enforce_path_through_barrier: true
  cache_size: 50000
reward: ${cls:flipper_training.rl_rewards.rewards.PotentialGoalWithSideLatentPreference}
reward_opts:
  goal_reached_reward: 14
  failed_reward: -14
  potential_coef: 27.279373033235267
  gamma: ${gae_opts.gamma}
  step_penalty: -0.32698437193572233
  side_bonus_coef: 0.1
policy_config: ${cls:flipper_training.policies.mlp_policy.MLPPolicyConfig}
policy_opts:
  share_encoder: false
  apply_baselines_init: true
  actor_mlp_opts:
    num_hidden: 2
    hidden_dim: 64
    layernorm: false
  value_mlp_opts:
    num_hidden: 2
    hidden_dim: 64
    layernorm: true
  actor_optimizer_opts:
    lr: 0.0002
    weight_decay: 0.0001
  value_optimizer_opts:
    lr: 0.002
    weight_decay: 0.0001
policy_weights_path: modified_networks/transferred_with_preference/policy.pth
vecnorm_weights_path: modified_networks/transferred_with_preference/vecnorm.pth
