name: trunk_with_previous_action_dedicated${seed}
seed: 42
device: cuda
reward: ${cls:flipper_training.rl_rewards.rewards.PotentialGoal}
comment: Trunk SOTA config with previous action observation, concatenated to the state embedding
gae_opts:
  gamma: 0.999
  lmbda: 0.95
  average_gae: false
  skip_existing: false
grid_res: 0.05
ppo_opts:
  critic_coef: 1
  clip_epsilon: 0.2
  entropy_coef: 0.02
  entropy_bonus: true
  separate_losses: false
  loss_critic_type: smooth_l1
  normalize_advantage: true
max_coord: 3.2
objective: ${cls:flipper_training.rl_objectives.trunk_crossing.TrunkCrossing}
optimizer: ${cls:torch.optim.AdamW}
scheduler: ${cls:torch.optim.lr_scheduler.LinearLR}
use_wandb: true
num_robots: 256
world_opts:
  k_stiffness: 35000
  k_friction_lat: 0.5
  k_friction_lon: 0.8
engine_opts:
  dt: 0.007
  damping_alpha: 5
policy_opts:
  share_encoder: false
  actor_mlp_opts:
    layernorm: false
    hidden_dim: 64
    num_hidden: 2
  value_mlp_opts:
    layernorm: true
    hidden_dim: 64
    num_hidden: 2
  actor_optimizer_opts:
    lr: 0.0001603100926368119
    weight_decay: 0.0001
  apply_baselines_init: true
  value_optimizer_opts:
    lr: 0.002027103877870638
    weight_decay: 0.0001
reward_opts:
  gamma: ${gae_opts.gamma}
  step_penalty: -0.24508094900269353
  failed_reward: -4.185834036649192
  potential_coef: 42.65164641109597
  goal_reached_reward: 7.00220498001836
observations:
  - cls: ${cls:flipper_training.observations.robot_state.LocalStateVector}
    opts:
      apply_noise: true
      noise_scale: 1.0e-05
      encoder_opts:
        layernorm: true
        hidden_dim: 64
        num_hidden: 2
        output_dim: 64
  - cls: ${cls:flipper_training.observations.heightmap.Heightmap}
    opts:
      interval:
        - -1
        - 1
      apply_noise: true
      noise_scale: 1.0e-05
      encoder_opts:
        output_dim: 64
      percep_shape:
        - 64
        - 64
      percep_extent:
        - 1
        - 1
        - -1
        - -1
      normalize_to_interval: false
  - cls: ${cls:flipper_training.observations.previous_action.PreviousAction}
    opts:
      apply_noise: true
      noise_scale: 1.0e-05
      encoder_opts:
        layernorm: true
        hidden_dim: 32
        num_hidden: 1
        output_dim: 32
total_frames: ${mul:5242880,5}
vecnorm_opts:
  eps: 0.0001
  decay: 0.99
heightmap_gen: ${ cls:flipper_training.heightmaps.trunks.TrunkHeightmapGenerator}
max_grad_norm: 0.5
policy_config: ${cls:flipper_training.policies.mlp_policy.MLPPolicyConfig}
max_eval_steps: 500
objective_opts:
  cache_size: 20000
  goal_z_offset: 0.05
  start_z_offset: 0.2
  max_dist_to_goal: 4
  min_dist_to_goal: 2
  init_joint_angles: random
  max_feasible_roll: 1.5
  max_feasible_pitch: 1.5
  goal_reached_threshold: 0.2
  iteration_limit_factor: 5
  start_position_orientation: towards_goal
  resample_random_joint_angles_on_reset: true
scheduler_opts:
  end_factor: 0.2345794068901917
  total_iters: ${intdiv:${total_frames},${mul:${time_steps_per_batch},${num_robots}}}
  start_factor: 1
training_dtype: ${dtype:float32}
use_tensorboard: false
epochs_per_batch: 5
robot_model_opts:
  kind: marv
  mesh_voxel_size: 0.01
  points_per_body: 512
  points_per_driving_part: 384
  wheel_assignment_margin: 0.02
  linear_track_assignment_margin: 0.05
vecnorm_on_reward: true
heightmap_gen_opts:
  exp: 6
  max_trunk_width: 1.2
  min_trunk_width: 0.6
  max_trunk_height: 0.3
  min_trunk_height: 0.15
  max_dist_from_origin: 0.5
  trunk_deadzone_width: 0.5
data_collector_opts:
  split_trajs: false
  compile_policy: false
  exploration_type: RANDOM
engine_compile_opts:
  atol: 0.1
  rtol: 1.0e-06
  options:
    triton.cudagraphs: true
  fullgraph: true
  benchmark_iters: 1000
  correctness_iters: 10
eval_and_save_every: 10
frames_per_sub_batch: 4096
time_steps_per_batch: 128
engine_iters_per_env_step: 4
eval_repeats_after_training: 1
